require 'docker'
require 'serverspec'
require 'redis'

REDIS_PORT = 6379

describe "Dockerfile" do
  before(:all) do
    @image = Docker::Image.build_from_dir('.')

    set :os, family: :redhat
    set :backend, :docker
    set :docker_image, @image.id
  end

  describe file('/etc/centos-release') do
    it { should be_file }
  end

end
